name: "RELEASE_PACKAGE_NOTO_SERIF_DEVANAGARI_VERSION"
namespace: "text"
description: "Version of the Noto Serif Devanagari font."
value: {
  string_value: "2.001"
}
workflow: PREBUILT
containers: "system"