name: "RELEASE_SVN_BLAZER"
namespace: "android_release"
description: "Using this flag to set build SVN(Software Version Number) value for BLAZER under VENDOR"
value: {
  string_value: "00"
}
workflow: MANUAL
containers: "vendor"
