name: "RELEASE_TELEPHONY_MODULE"
namespace: "telephony"
description: "If true, then telephony module is enabled as an apex"
value: {
  bool_value: false
}
workflow: LAUNCH
containers: "product"
containers: "system"
containers: "system_ext"
containers: "vendor"
