name: "RELEASE_SOONG_ONLY_BLUEJAY"
namespace: "build"
description: "Enables building BLUEJAY with soong-only (no make) builds"
value: {
  bool_value: false
}
workflow: LAUNCH
containers: "product"
containers: "system"
containers: "system_ext"
containers: "vendor"
