name: "RELEASE_SOONG_OS_VARIANT_ON_DEMAND"
namespace: "build"
description: "Switches the non primary os variant creation from frontloaded to on-demand."
value: {
  bool_value: false
}
workflow: LAUNCH
containers: "product"
containers: "system"
containers: "system_ext"
containers: "vendor"
