name: "RELEASE_UPROBESTATS_SERVICE"
namespace: "responsible_apis"
description: "If true, then the system service UprobeStatsService is enabled"
value: {
  bool_value: false
}
workflow: LAUNCH
containers: "product"
containers: "system"
containers: "system_ext"
containers: "vendor"
containers: "com.android.uprobestats"
