name: "RELEASE_ART_COMPILE_CONNECTIVITY_SERVICE_SPEED_PROFILE"
namespace: "art_cloud"
description: "b/241823638: Flag to enable ART Speed Profile compilation for Connectivity module service."
value: {
  bool_value: false
}
workflow: LAUNCH
containers: "system"
