name: "RELEASE_NPUMANAGER_MODULE"
namespace: "machine_learning"
description: "If true, then npumanager module is enabled as an apex"
value: {
  bool_value: false
}
workflow: LAUNCH
containers: "product"
containers: "system"
containers: "system_ext"
containers: "vendor"
