name: "RELEASE_PLATFORM_PROSPECTIVE_SDK_VERSION_FULL"
namespace: "android_sdk"
description: "The prospective major and minor SDK versions of the platform, e.g. 35.0 or 123.45. This is used to determine the SDK version of the APIs found in source (as opposed to prebuilts) should be attributed to. If the release has been finalized, this flag is not set and metalava should not use the sources to determine the API surface. Note: the prospective SDK value is a build time implementation detail, and must never be visible on device."
workflow: MANUAL
containers: "product"
containers: "system"
containers: "system_ext"
containers: "vendor"
