name: "RELEASE_SVN_RANGO"
namespace: "android_release"
description: "Using this flag to set build SVN(Software Version Number) value for RANGO under VENDOR"
value: {
  string_value: "00"
}
workflow: MANUAL
containers: "vendor"
