name: "RELEASE_WIDEVINE_CUTTLEFISH_L1"
namespace: "media_drm"
description: "Enable Widevine L1 on Cuttlefish."
value: {
  bool_value: false
}
workflow: LAUNCH
containers: "product"
containers: "system"
containers: "system_ext"
containers: "vendor"