name: "RELEASE_ACONFIG_FINGERPRINT_CPP"
namespace: "core_experiments_team_internal"
description: "Control checking the fingerprint in the cpp codegen."
workflow: LAUNCH
containers: "product"
containers: "system"
containers: "system_ext"
containers: "vendor"
