name: "RELEASE_BUILD_AFDO_ENABLE_MFS"
namespace: "llvm_and_toolchains"
description: "Enable machine function splitter (MFS) optimization"
value: {
  bool_value: false
}
workflow: LAUNCH
containers: "product"
containers: "system"
containers: "system_ext"
containers: "vendor"
