name: "RELEASE_PACKAGE_NOTO_SERIF_GURMUKHI_VERSION"
namespace: "text"
description: "Version of the Noto Serif Gurmukhi font."
value: {
  string_value: "2.001"
}
workflow: PREBUILT
containers: "system"