name: "RELEASE_APEX_CONTRIBUTIONS_WEBAPP"
namespace: "lse_desktop_experience"
description: "Specify whether to use prebuilts or source for this module"
workflow: MANUAL
containers: "product"
containers: "system"
containers: "system_ext"
containers: "vendor"
